Controllers/AuthorController.cs
using BookStore2024.Data;
using BookStore2024.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookStore2024.Controllers
{
	public class AuthorController : Controller
    {
		private readonly BookStoreContext DBContext;
		public AuthorController(BookStoreContext DatabaseContext) => DBContext = DatabaseContext;
		public async Task<IActionResult> Index(string sortOrder,string currentFilter,string searchString,int pageNumber = 1)
		{
			//if (searchString != null)
			//{
			//	pageNumber = 1;
			//}
			//else
			//{
			//	searchString = currentFilter;
			//}

			var AuthorQuery = DBContext.ViewAuthorDetails.AsQueryable();
			int pageSize = 18;
            var data = AuthorQuery.Select(p => new AuthorVM
            {
				AuthorId = p.AuthorId,
                AuthorName = p.AuthorName,
                ProfileImageUrl = p.ProfileImageUrl,
                AuthorDescription = p.AuthorDescription,
                PublishedBook = p.PublishedBooks ?? 0
			});
			ViewBag.totalAuthor = data.Count();
			return View(await PaginatedList<AuthorVM>.CreateAsync(data, pageNumber, pageSize));
        }

		public IActionResult Detail(int DetailId)
		{
			var AuthorQuery = DBContext.ViewAuthorDetails.Where(p => p.AuthorId == DetailId).SingleOrDefault();
			if (AuthorQuery == null)
			{
				TempData["Message"] = $"Could not find author have id: {DetailId} or product does not exist";
				return Redirect("/404");
			}
			var data = new AuthorVM
			{
				AuthorId = AuthorQuery.AuthorId,
				AuthorName = AuthorQuery.AuthorName,
				ProfileImageUrl = AuthorQuery.ProfileImageUrl,
				AuthorDescription = AuthorQuery.AuthorDescription,
				PublishedBook = AuthorQuery.PublishedBooks ?? 0
			};

			return View(data);
		}
	}
}

Controllers/BlogController.cs
using BookStore2024.Data;
using BookStore2024.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookStore2024.Controllers
{
	public class BlogController : Controller
	{
		private readonly BookStoreContext DBContext;
		public BlogController(BookStoreContext DatabaseContext) => DBContext = DatabaseContext;
		public IActionResult Index()
		{
			var BlogQuery = DBContext.ViewBlogDetails.AsQueryable();

			var data = BlogQuery.OrderByDescending(p => p.Views).Take(9).Select(p => new BlogVM
			{
				BlogId = p.BlogId,
				BlogTitle = p.BlogTitle,
				BlogDescription = p.BlogDescription,
				Content = p.BlogContent,
				AuthorId = p.AuthorId,
				ImgUrl = p.ImgUrl,
				Views = p.Views,
				AuthorName = p.AuthorName
			});

			return View(data);
		}
		public IActionResult Detail(int DetailID)
		{
			var BlogQuery = DBContext.ViewBlogDetails.AsQueryable().Where(p => p.BlogId == DetailID);

			var data = BlogQuery.Select(p => new BlogVM
			{
				BlogId = p.BlogId,
				BlogTitle = p.BlogTitle,
				BlogDescription = p.BlogDescription,
				Content = p.BlogContent,
				AuthorId = p.AuthorId,
				ImgUrl = p.ImgUrl,
				Views = p.Views,
				AuthorName = p.AuthorName
			}).SingleOrDefault();

			return View(data);
		}
	}
}

Controllers/ProductsController.cs
using BookStore2024.Data;
using BookStore2024.ViewModels;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore2024.Controllers
{
    public class ProductsController : Controller
    {
        private readonly BookStoreContext DBContext;
        public ProductsController(BookStoreContext DatabaseContext) => DBContext = DatabaseContext;
        int pageSize = 8;
        public async Task<IActionResult> Index(int? pageNumber, int? category, int? genre)
        {

            var ProductsQuery = DBContext.ViewBookDetails.AsQueryable();

            if (category.HasValue)
            {
                ProductsQuery = ProductsQuery.Where(p => p.CategoryId == category.Value);
            }
            if (genre.HasValue)
            {
                ProductsQuery = ProductsQuery.Where(p => p.GenreId == genre.Value);
            }

            var data = ProductsQuery.Select(p => new ProductVM
            {
                CategoryId = p.CategoryId,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName,
                BookDetailId = p.BookDetailId
            });
            ViewBag.PageSize = pageSize;
            ViewBag.totalProduct = data.Count();
            ViewBag.category = category;
			ViewBag.genre = genre;

			return View(await PaginatedList<ProductVM>.CreateAsync(data, pageNumber ?? 1, pageSize));
            //return View(data);
        }
        public IActionResult Search(string? searchString)
        {
            var ProductsQuery = DBContext.ViewBookDetails.AsQueryable();
            if (searchString != null)
            {
                ProductsQuery = ProductsQuery.Where(p => p.BookTitle.ToLower().Contains(searchString.ToLower()));
            }
            var data = ProductsQuery.Select(p => new ProductVM
            {
                BookDetailId = p.BookDetailId,
                CategoryId = p.CategoryId,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName
            }).ToList();

            return View(data);
        }
        public IActionResult Detail(int DetailId)
        {
            var record = DBContext.ViewBookDetails.Where(p => p.BookDetailId == DetailId).SingleOrDefault();
            if (record == null)
            {
                TempData["Message"] = $"Could not find product have id: {DetailId} or product does not exist";
                return Redirect("/404");
            }
            var data = new ProductVM
            {
                BookDetailId = record.BookDetailId,
                CategoryId = record.CategoryId,
                CategoryName = record.CategoryName,
                ProductName = record.BookTitle,
                ProductImg = record.BookImageUrl ?? "",
                AuthorId = record.AuthorId,
                AuthorName = record.AuthorName,
                ProfileImageUrl = record.ProfileImageUrl,
                Price = record.Price,
                Discount = record.Discount,
                FormatId = record.FormatId,
                FormatName = record.FormatName,
                GenreName = record.GenreName,
                GenreId = record.GenreId,
                Publisher = record.Publisher,
                ProductDescription = record.BookDescription,
                Language = record.Language,
                Pages = record.Pages,
                IllustrationsNote = record.IllustrationsNote,
                Isbn10 = record.Isbn10,
                Isbn13 = record.Isbn13,
                StockQuantity = record.StockQuantity,
                Views = record.Views
            };

            return View(data);
        }

        public async Task<IActionResult> BestSelling(int? pageNumber, int? category, int? genre)
        {
            var Query = DBContext.ViewTop20BestSellingBooks.AsQueryable();

            if (Query == null)
            {
                TempData["Message"] = $"Could not find product or product does not exist";
                return Redirect("/404");
            }

            var data = Query.Select(p => new ProductVM
            {
                BookDetailId = p.BookDetailId,
                CategoryId = p.CategoryId ?? 0,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName
            });
            ViewBag.PageSize = pageSize;
            ViewBag.totalProduct = data.Count();
            ViewBag.category = category;
			ViewBag.genre = genre;
			return View(await PaginatedList<ProductVM>.CreateAsync(data, pageNumber ?? 1, pageSize));
            //return View(data);
        }

        public async Task<IActionResult> WeeklySale(int? pageNumber, int? category, int? genre)
        {
            var Query = DBContext.ViewBookDetails.AsQueryable();

            if (Query == null)
            {
                TempData["Message"] = $"Could not find product or product does not exist";
                return Redirect("/404");
            }
            else
            {
                Query = Query.Where(p => p.Discount != 0);
            }

            var data = Query.Select(p => new ProductVM
            {
                BookDetailId = p.BookDetailId,
                CategoryId = p.CategoryId,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName
            });
            ViewBag.PageSize = pageSize;
            ViewBag.totalProduct = data.Count();
            ViewBag.category = category;
			ViewBag.genre = genre;
			return View(await PaginatedList<ProductVM>.CreateAsync(data, pageNumber ?? 1, pageSize));
        }

        [Authorize]
        public IActionResult AddToWishList(int DetailId)
        {
            int customerId = int.Parse(User.FindFirst("UserID").Value);

            var wishItem = DBContext.TblUserWishlists.SingleOrDefault(p => p.BookDetailId == DetailId);
            if (wishItem != null) {
                return Redirect(Request.Headers["Referer"].ToString());
            }

            wishItem = new TblUserWishlist
            {
                UserId = customerId,
                BookDetailId = DetailId
            };
            DBContext.Database.BeginTransaction();
            try
            {
                DBContext.Database.CommitTransaction();
                DBContext.Add(wishItem);
                DBContext.SaveChanges();

                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch
            {
                DBContext.Database.RollbackTransaction();
            }
            return Redirect(Request.Headers["Referer"].ToString());
        }

    }
}

Controllers/UserController.cs
using AutoMapper;
using BookStore2024.Data;
using BookStore2024.Helpers;
using BookStore2024.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using System.Security.Claims;

namespace BookStore2024.Controllers
{
    public class UserController : Controller
    {
        private readonly BookStoreContext DBContext;
        private readonly IMapper _mapper;
        public UserController(BookStoreContext DatabaseContext, IMapper mapper) {
            DBContext = DatabaseContext;
            _mapper = mapper;
        }

        #region Register
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(RegisterVM regisData, IFormFile? ProfileImageUrl)
        {
            if (ModelState.IsValid)
            {
                var record = DBContext.TblUsers.Where(p => p.Email == regisData.Email).SingleOrDefault();
                if (record != null)
                {
                    TempData["Message"] = $"Email has already been registered previously";
                    return View();
                }
                try
                {
                    var User = _mapper.Map<TblUser>(regisData);

                    if (ProfileImageUrl != null)
                    {
                        User.ProfileImageUrl = ProjectUtil.UploadImage(ProfileImageUrl, "users");
                    }
                    else { User.ProfileImageUrl = string.Empty; }

                    DBContext.Add(User);
                    DBContext.SaveChanges();

                    //string g = User.ProfileImageUrl;
                    //string z = regisData.Password;
                    //string x = regisData.ShippingAddress;
                    //string y = regisData.UserName;

                    //TempData["Message"] = $"Register Success!";
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    TempData["Message"] = $"some information are provided incorrectly";
                }
            }
            return View();
        }
        #endregion

        #region Login
        [HttpGet]
        public IActionResult Login()
        {
            //return ViewComponent("UserLogin");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginVM loginInfo)
        {
            if(ModelState.IsValid)
            {
                var user = DBContext.TblUsers.SingleOrDefault( u => u.Email == loginInfo.Email);
                if (user == null)
                {
                    //ModelState.AddModelError("Error", "Invalid user");
                    
                    TempData["Message"] = "Invalid user!";
                    return RedirectToAction("Login");
                }
                else
                {
                    if(user.Password != loginInfo.Password)
                    {
                        TempData["Message"] = "Incorect password!";
                        ViewBag.Msg = Convert.ToString(TempData["Message"]);
                        return RedirectToAction("Login");
                    }
                    else
                    {
                        var claims = new List<Claim>
                        {
                            new Claim("Email",user.Email),
                            new Claim(ClaimTypes.Name,user.UserName),
                            new Claim("UserID",user.UserId.ToString()),
                            new Claim("ProfileImageUrl",user.ProfileImageUrl ?? ""),
                            new Claim("Address",user.UserAddress ?? "address error"),

                            new Claim(ClaimTypes.Role,"Customer")
                        };
                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                        //TempData["Message"] = "login success!";
                        await HttpContext.SignInAsync(claimsPrincipal);

                        ViewBag.UserImg = user.ProfileImageUrl ?? "../user/img-01.jpg";
                        return RedirectToAction("Index","Home");
                    }
                }
            }
            await Response.WriteAsync("<script>alert ('Invalid user or Incorect Password')</script>");
            return RedirectToAction("Login");
        }
        #endregion
        [Authorize]
        public IActionResult Profile()
        {
            int userID = int.Parse(User.FindFirst("UserID").Value);
           
            var listWishID = DBContext.TblUserWishlists.Where(p => p.UserId == userID).ToList();

            List<ProductVM> products = new List<ProductVM>();

            foreach (var item in listWishID)
            {
                var record = DBContext.ViewBookDetails.Where(p => p.BookDetailId == item.BookDetailId).SingleOrDefault();
                if (record == null)
                {
                    TempData["Message"] = $"Could not find product have id or product does not exist";
                    return Redirect("/404");
                }
                var product = new ProductVM
                {
                    BookDetailId = record.BookDetailId,
                    CategoryId = record.CategoryId,
                    CategoryName = record.CategoryName,
                    ProductName = record.BookTitle,
                    ProductImg = record.BookImageUrl ?? "",
                    AuthorId = record.AuthorId,
                    AuthorName = record.AuthorName,
                    ProfileImageUrl = record.ProfileImageUrl,
                    Price = record.Price,
                    Discount = record.Discount,
                    FormatId = record.FormatId,
                    FormatName = record.FormatName,
                    GenreName = record.GenreName,
                    GenreId = record.GenreId,
                    Publisher = record.Publisher,
                    ProductDescription = record.BookDescription,
                    Language = record.Language,
                    Pages = record.Pages,
                    IllustrationsNote = record.IllustrationsNote,
                    Isbn10 = record.Isbn10,
                    Isbn13 = record.Isbn13,
                    StockQuantity = record.StockQuantity,
                    Views = record.Views
                };
                products.Add(product);
            }
            return View(products);
        }
        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/_Footer.cshtml
<!--************************************
		Footer Start
*************************************-->
<footer id="tg-footer" class="tg-footer tg-haslayout">
	<div class="tg-footerarea">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<ul class="tg-clientservices">
						<li class="tg-devlivery">
							<span class="tg-clientserviceicon"><i class="icon-rocket"></i></span>
							<div class="tg-titlesubtitle">
								<h3>Fast Delivery</h3>
								<p>Shipping Worldwide</p>
							</div>
						</li>
						<li class="tg-discount">
							<span class="tg-clientserviceicon"><i class="icon-tag"></i></span>
							<div class="tg-titlesubtitle">
								<h3>Open Discount</h3>
								<p>Offering Open Discount</p>
							</div>
						</li>
						<li class="tg-quality">
							<span class="tg-clientserviceicon"><i class="icon-leaf"></i></span>
							<div class="tg-titlesubtitle">
								<h3>Eyes On Quality</h3>
								<p>Publishing Quality Work</p>
							</div>
						</li>
						<li class="tg-support">
							<span class="tg-clientserviceicon"><i class="icon-heart"></i></span>
							<div class="tg-titlesubtitle">
								<h3>24/7 Support</h3>
								<p>Serving Every Moments</p>
							</div>
						</li>
					</ul>
				</div>
				<div class="tg-threecolumns">
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
						<div class="tg-footercol">
							<strong class="tg-logo"><a href="javascript:void(0);"><img src="../images/flogo.png" alt="image description"></a></strong>
							<ul class="tg-contactinfo">
								<li>
									<i class="icon-apartment"></i>
									<address>Suit # 07, Rose world Building, Street # 02, AT246T Manchester</address>
								</li>
								<li>
									<i class="icon-phone-handset"></i>
									<span>
										<em>0800 12345 - 678 - 89</em>
										<em>+4 1234 - 4567 - 67</em>
									</span>
								</li>
								<li>
									<i class="icon-clock"></i>
									<span>Serving 7 Days A Week From 9am - 5pm</span>
								</li>
								<li>
									<i class="icon-envelope"></i>
									<span>
										<em><a href="mailto:support@domain.com">support@domain.com</a></em>
										<em><a href="mailto:info@domain.com">info@domain.com</a></em>
									</span>
								</li>
							</ul>
							<ul class="tg-socialicons">
								<li class="tg-facebook"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
								<li class="tg-twitter"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
								<li class="tg-linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
								<li class="tg-googleplus"><a href="javascript:void(0);"><i class="fa fa-google-plus"></i></a></li>
								<li class="tg-rss"><a href="javascript:void(0);"><i class="fa fa-rss"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
						<div class="tg-footercol tg-widget tg-widgetnavigation">
							<div class="tg-widgettitle">
								<h3>Shipping And Help Information</h3>
							</div>
							<div class="tg-widgetcontent">
								<ul>
									<li><a href="javascript:void(0);">Terms of Use</a></li>
									<li><a href="javascript:void(0);">Terms of Sale</a></li>
									<li><a href="javascript:void(0);">Returns</a></li>
									<li><a href="javascript:void(0);">Privacy</a></li>
									<li><a href="javascript:void(0);">Cookies</a></li>
									<li><a href="javascript:void(0);">Contact Us</a></li>
									<li><a href="javascript:void(0);">Our Affiliates</a></li>
									<li><a href="javascript:void(0);">Vision &amp; Aim</a></li>
								</ul>
								<ul>
									<li><a href="javascript:void(0);">Our Story</a></li>
									<li><a href="javascript:void(0);">Meet Our Team</a></li>
									<li><a href="javascript:void(0);">FAQ</a></li>
									<li><a href="javascript:void(0);">Testimonials</a></li>
									<li><a href="javascript:void(0);">Join Our Team</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
						<div class="tg-footercol tg-widget tg-widgettopsellingauthors">
							<div class="tg-widgettitle">
								<h3>Top Selling Authors</h3>
							</div>
							<div class="tg-widgetcontent">
								<ul>
									<li>
										<figure><a href="javascript:void(0);"><img src="../images/author/imag-09.jpg" alt="image description"></a></figure>
										<div class="tg-authornamebooks">
											<h4><a href="javascript:void(0);">Jude Morphew</a></h4>
											<p>21,658 Published Books</p>
										</div>
									</li>
									<li>
										<figure><a href="javascript:void(0);"><img src="../images/author/imag-10.jpg" alt="image description"></a></figure>
										<div class="tg-authornamebooks">
											<h4><a href="javascript:void(0);">Shaun Humes</a></h4>
											<p>20,257 Published Books</p>
										</div>
									</li>
									<li>
										<figure><a href="javascript:void(0);"><img src="../images/author/imag-11.jpg" alt="image description" style="height: 70px; width: auto;"></a></figure>
										<div class="tg-authornamebooks">
											<h4><a href="javascript:void(0);">Kathrine Culbertson</a></h4>
											<p>15,686 Published Books</p>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="tg-newsletter">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
					<h4>Signup Newsletter!</h4>
					<h5>Consectetur adipisicing elit sed do eiusmod tempor incididunt.</h5>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
					<form class="tg-formtheme tg-formnewsletter">
						<fieldset>
							<input type="email" name="email" class="form-control" placeholder="Enter Your Email ID">
							<button type="button"><i class="icon-envelope"></i></button>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="tg-footerbar">
		<a id="tg-btnbacktotop" class="tg-btnbacktotop" href="javascript:void(0);"><i class="icon-chevron-up"></i></a>
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<span class="tg-paymenttype"><img src="../images/paymenticon.png" alt="image description"></span>
					<span class="tg-copyright">2017 All Rights Reserved By &copy; Book Library</span>
				</div>
			</div>
		</div>
	</div>
</footer>
<!--************************************
		Footer End
*************************************-->

Views/Shared/_Header.cshtml
<!--************************************
                Header Start
*************************************-->
<header id="tg-header" class="tg-header tg-haslayout">
    <div class="tg-topbar">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="tg-addnav">
                        <li>
                            <a href="javascript:void(0);">
                                <i class="icon-envelope"></i>
                                <em>Contact</em>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);">
                                <i class="icon-question-circle"></i>
                                <em>Help</em>
                            </a>
                        </li>
                    </ul>
                    <div class="dropdown tg-themedropdown tg-currencydropdown">
                        <a href="javascript:void(0);" id="tg-currenty" class="tg-btnthemedropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="icon-earth"></i>
                            <span>Currency</span>
                        </a>
                        <ul class="dropdown-menu tg-themedropdownmenu" aria-labelledby="tg-currenty">
                            <li>
                                <a href="javascript:void(0);">
                                    <i>£</i>
                                    <span>British Pound</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);">
                                    <i>$</i>
                                    <span>Us Dollar</span>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0);">
                                    <i>€</i>
                                    <span>Euro</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                   @await Component.InvokeAsync("UserLogin")
                </div>
            </div>
        </div>
    </div>
    <div class="tg-middlecontainer">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <strong class="tg-logo"><a asp-action="index" asp-controller="Home"><img src="../images/logo.png" alt="company name here"></a></strong>
                    <div class="tg-wishlistandcart">
                        <div class="dropdown tg-themedropdown tg-wishlistdropdown">
                            <a href="javascript:void(0);" id="tg-wishlisst" class="tg-btnthemedropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="tg-themebadge">0</span>
                                <i class="icon-heart"></i>
                                <span>Wishlist</span>
                            </a>
                            <div class="dropdown-menu tg-themedropdownmenu" aria-labelledby="tg-wishlisst">
                                <div class="tg-description"><p>No products were added to the wishlist!</p></div>
                            </div>
                        </div>

                        @await Component.InvokeAsync("Minicart")
                    </div>
                    <div class="tg-searchbox">
                        @await Html.PartialAsync("_Search")
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tg-navigationarea">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <nav id="tg-nav" class="tg-nav">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#tg-navigation" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div id="tg-navigation" class="collapse navbar-collapse tg-navigation">
                            <ul>
                                @await Component.InvokeAsync("MegaMenu")
                                <li>
                                    <a asp-action="index" asp-controller="Home">Home</a>
                                </li>
                                <li>
                                    <a asp-action="index" asp-controller="Author">Authors</a>
                                </li>
                                <li>
                                    <a asp-action="BestSelling" asp-controller="Products">Best Selling</a>
                                </li>
                                <li>
                                    <a asp-action="WeeklySale" asp-controller="Products">Weekly Sale</a>
                                </li>
                                <li>
                                    <a asp-action="index" asp-controller="Products">All Products</a>
                                </li>
                                <li>
                                    <a asp-action="index" asp-controller="Blog">News and Blogs</a>
                                </li>
                               @*  <li>
                                    <a asp-action="Register" asp-controller="User">Test Regis</a>
                                </li> *@
                                <li>
                                    <a asp-action="AboutUs" asp-controller="Home">About Us</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>

<!--************************************
                Header End
*************************************-->

Views/Shared/_Search.cshtml
<form class="tg-formtheme tg-formsearch" asp-action="Search" asp-controller="Products">
    <fieldset>
        <input type="text" name="searchString" class="typeahead form-control" placeholder="Search by title">
        <button type="submit"><i class="icon-magnifier"></i></button>
    </fieldset>
</form>