Controllers/AuthorController.cs
using BookStore2024.Data;
using BookStore2024.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookStore2024.Controllers
{
	public class AuthorController : Controller
    {
		private readonly BookStoreContext DBContext;
		public AuthorController(BookStoreContext DatabaseContext) => DBContext = DatabaseContext;
		public async Task<IActionResult> Index(string sortOrder,string currentFilter,string searchString,int pageNumber = 1)
		{
			//if (searchString != null)
			//{
			//	pageNumber = 1;
			//}
			//else
			//{
			//	searchString = currentFilter;
			//}

			var AuthorQuery = DBContext.ViewAuthorDetails.AsQueryable();
			int pageSize = 18;
            var data = AuthorQuery.Select(p => new AuthorVM
            {
				AuthorId = p.AuthorId,
                AuthorName = p.AuthorName,
                ProfileImageUrl = p.ProfileImageUrl,
                AuthorDescription = p.AuthorDescription,
                PublishedBook = p.PublishedBooks ?? 0
			});
			ViewBag.totalAuthor = data.Count();
			return View(await PaginatedList<AuthorVM>.CreateAsync(data, pageNumber, pageSize));
        }

		public IActionResult Detail(int DetailId)
		{
			var AuthorQuery = DBContext.ViewAuthorDetails.Where(p => p.AuthorId == DetailId).SingleOrDefault();
			if (AuthorQuery == null)
			{
				TempData["Message"] = $"Could not find author have id: {DetailId} or product does not exist";
				return Redirect("/404");
			}
			var data = new AuthorVM
			{
				AuthorId = AuthorQuery.AuthorId,
				AuthorName = AuthorQuery.AuthorName,
				ProfileImageUrl = AuthorQuery.ProfileImageUrl,
				AuthorDescription = AuthorQuery.AuthorDescription,
				PublishedBook = AuthorQuery.PublishedBooks ?? 0
			};

			return View(data);
		}
	}
}

Controllers/CartController.cs
using BookStore2024.Data;
using BookStore2024.ViewModels;
using Microsoft.AspNetCore.Mvc;
using BookStore2024.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace BookStore2024.Controllers
{
    public class CartController : Controller
    {
        private readonly BookStoreContext DBContext;
        public CartController(BookStoreContext DatabaseContext) => DBContext = DatabaseContext;
        
        public List<CartItemVM> ListProductsInCart => HttpContext.Session.Get<List<CartItemVM>>(Constants.SESSION_KEY) ?? new List<CartItemVM>();

        public IActionResult Index()
        {
            return View(ListProductsInCart);
        }
        [Authorize]
        public IActionResult AddtoCart(int productDetailId, int quantity = 1)
        {
            var CartList = ListProductsInCart;

            var item = CartList.SingleOrDefault(p => p.BookDetailId == productDetailId);
            
            if (item == null) //nếu chưa có sản phẩm có (id == productDetailId) đó ở trong cart
            {
                var product = DBContext.ViewBookDetails.SingleOrDefault(p => p.BookDetailId == productDetailId); //kiểm tra sản phẩm đó có tồn tại hay không
                if (product == null) //kiểm tra id có tồn tại hay không
                {
                    TempData["Message"] = $"Could not find product have id: {productDetailId} or product does not exist";
                    return Redirect("/404");
                }

                item = new CartItemVM { // nếu tồn tại thì tạo mới và thêm vào giỏ hàng
                    BookDetailId = productDetailId,
                    ProductName = product.BookTitle,
                    ProductImg = product.BookImageUrl,
                    FormatName = product.FormatName,
                    Price = product.Price - (product.Discount ?? 0), //gía được truyền vào view là giá sau khi đã chiết khấu (discount rồi)
                    Quantity = (quantity > 0) ? quantity : 1,
                };

                CartList.Add(item);
            }
            else { item.Quantity += (quantity > 0) ? quantity : 1; }//nếu tồn tại sp trong giỏ hàng rồi thì cập nhật lại số lượng
            HttpContext.Session.Set(Constants.SESSION_KEY, CartList);

            return Redirect(Request.Headers["Referer"].ToString());
            //return NoContent();
        }
		public ActionResult RemoveItem(int productDetailId)
        {
            var CartList = ListProductsInCart;

            var item = CartList.SingleOrDefault(p => p.BookDetailId == productDetailId);

            if (item != null) 
            {
                CartList.Remove(item);
                HttpContext.Session.Set(Constants.SESSION_KEY, CartList);
            }
            return NoContent();
        }
        
        public IActionResult increaseQuantity(int productDetailId)
        {
            var CartList = ListProductsInCart;
            var item = CartList.SingleOrDefault(p => p.BookDetailId == productDetailId);
            if (item != null)
            {
                item.Quantity ++;
            }
            HttpContext.Session.Set(Constants.SESSION_KEY, CartList);
            return NoContent();
        }

        public IActionResult decreaseQuantity(int productDetailId)
        {
            var CartList = ListProductsInCart;
            var item = CartList.SingleOrDefault(p => p.BookDetailId == productDetailId);
            if (item != null)
            {
                if(item.Quantity > 1) { item.Quantity--; }
            }
            HttpContext.Session.Set(Constants.SESSION_KEY, CartList);
            return NoContent();
        }

        public IActionResult ClearCart()
        {
			var CartList = new List<CartItemVM>();
			HttpContext.Session.Set(Constants.SESSION_KEY, CartList);

            return Redirect(Request.Headers["Referer"].ToString());
            //return NoContent();
            //return RedirectToAction("Index");
        }

        //[HttpGet]
        //[Authorize]
        //public IActionResult CheckOut()
        //{
        //    return View(ListProductsInCart);
        //    return RedirectToAction("Index", "Home");
        //}

        [HttpPost]
        [Authorize]
        public IActionResult CheckOut(CheckOutVM formData)
        {
            int customerId = int.Parse(User.FindFirst("UserID").Value);
            int OrderID = 0;

            var customer = new TblUser();

            customer = DBContext.TblUsers.SingleOrDefault(p => p.UserId == customerId);

            var newOrder = new TblOrder
            {
                UserId = customerId,
                OrderDate = DateOnly.FromDateTime(DateTime.Now),
                TotalAmount = formData.total,
                OrderStatus = "Đã đặt hàng",
                ShippingMethod = "Giao hàng tiêu chuẩn",
                PaymentMethod = 1,
                ShippingFee = 5,
                ShippingAddress = formData.address
            };
            
            DBContext.Database.BeginTransaction();
            try
            {
                DBContext.Database.CommitTransaction();
                DBContext.Add(newOrder);
                DBContext.SaveChanges();
                
                var orderDetails = new List<TblOrderDetail>();

                foreach (var item in ListProductsInCart)
                {
                    orderDetails.Add(new TblOrderDetail
                    {
                        OrderId = newOrder.OrderId,
                        BookDetailId = item.BookDetailId,
                        Quantity = item.Quantity
                    });
                }
                DBContext.AddRange(orderDetails);
                DBContext.SaveChanges();
                OrderID = newOrder.OrderId;
                var CartList = new List<CartItemVM>();
                HttpContext.Session.Set(Constants.SESSION_KEY, CartList);

                return View("CheckOutSuccess");
            }
            catch
            {
                DBContext.Database.RollbackTransaction();
            }
            ViewBag.OrderID = OrderID;
            ViewBag.customerId = customerId;
            return View("CheckOut", formData);
        }

    }
}

Controllers/ProductsController.cs
using BookStore2024.Data;
using BookStore2024.ViewModels;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore2024.Controllers
{
    public class ProductsController : Controller
    {
        private readonly BookStoreContext DBContext;
        public ProductsController(BookStoreContext DatabaseContext) => DBContext = DatabaseContext;
        int pageSize = 8;
        public async Task<IActionResult> Index(int? pageNumber, int? category, int? genre)
        {

            var ProductsQuery = DBContext.ViewBookDetails.AsQueryable();

            if (category.HasValue)
            {
                ProductsQuery = ProductsQuery.Where(p => p.CategoryId == category.Value);
            }
            if (genre.HasValue)
            {
                ProductsQuery = ProductsQuery.Where(p => p.GenreId == genre.Value);
            }

            var data = ProductsQuery.Select(p => new ProductVM
            {
                CategoryId = p.CategoryId,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName,
                BookDetailId = p.BookDetailId
            });
            ViewBag.PageSize = pageSize;
            ViewBag.totalProduct = data.Count();
            ViewBag.category = category;
			ViewBag.genre = genre;

			return View(await PaginatedList<ProductVM>.CreateAsync(data, pageNumber ?? 1, pageSize));
            //return View(data);
        }
        public IActionResult Search(string? searchString)
        {
            var ProductsQuery = DBContext.ViewBookDetails.AsQueryable();
            if (searchString != null)
            {
                ProductsQuery = ProductsQuery.Where(p => p.BookTitle.ToLower().Contains(searchString.ToLower()));
            }
            var data = ProductsQuery.Select(p => new ProductVM
            {
                BookDetailId = p.BookDetailId,
                CategoryId = p.CategoryId,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName
            }).ToList();

            return View(data);
        }
        public IActionResult Detail(int DetailId)
        {
            var record = DBContext.ViewBookDetails.Where(p => p.BookDetailId == DetailId).SingleOrDefault();
            if (record == null)
            {
                TempData["Message"] = $"Could not find product have id: {DetailId} or product does not exist";
                return Redirect("/404");
            }
            var data = new ProductVM
            {
                BookDetailId = record.BookDetailId,
                CategoryId = record.CategoryId,
                CategoryName = record.CategoryName,
                ProductName = record.BookTitle,
                ProductImg = record.BookImageUrl ?? "",
                AuthorId = record.AuthorId,
                AuthorName = record.AuthorName,
                ProfileImageUrl = record.ProfileImageUrl,
                Price = record.Price,
                Discount = record.Discount,
                FormatId = record.FormatId,
                FormatName = record.FormatName,
                GenreName = record.GenreName,
                GenreId = record.GenreId,
                Publisher = record.Publisher,
                ProductDescription = record.BookDescription,
                Language = record.Language,
                Pages = record.Pages,
                IllustrationsNote = record.IllustrationsNote,
                Isbn10 = record.Isbn10,
                Isbn13 = record.Isbn13,
                StockQuantity = record.StockQuantity,
                Views = record.Views
            };

            return View(data);
        }

        public async Task<IActionResult> BestSelling(int? pageNumber, int? category, int? genre)
        {
            var Query = DBContext.ViewTop20BestSellingBooks.AsQueryable();

            if (Query == null)
            {
                TempData["Message"] = $"Could not find product or product does not exist";
                return Redirect("/404");
            }

            var data = Query.Select(p => new ProductVM
            {
                BookDetailId = p.BookDetailId,
                CategoryId = p.CategoryId ?? 0,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName
            });
            ViewBag.PageSize = pageSize;
            ViewBag.totalProduct = data.Count();
            ViewBag.category = category;
			ViewBag.genre = genre;
			return View(await PaginatedList<ProductVM>.CreateAsync(data, pageNumber ?? 1, pageSize));
            //return View(data);
        }

        public async Task<IActionResult> WeeklySale(int? pageNumber, int? category, int? genre)
        {
            var Query = DBContext.ViewBookDetails.AsQueryable();

            if (Query == null)
            {
                TempData["Message"] = $"Could not find product or product does not exist";
                return Redirect("/404");
            }
            else
            {
                Query = Query.Where(p => p.Discount != 0);
            }

            var data = Query.Select(p => new ProductVM
            {
                BookDetailId = p.BookDetailId,
                CategoryId = p.CategoryId,
                CategoryName = p.CategoryName,
                ProductName = p.BookTitle,
                ProductImg = p.BookImageUrl ?? "",
                AuthorName = p.AuthorName,
                Price = p.Price,
                Discount = p.Discount,
                FormatName = p.FormatName
            });
            ViewBag.PageSize = pageSize;
            ViewBag.totalProduct = data.Count();
            ViewBag.category = category;
			ViewBag.genre = genre;
			return View(await PaginatedList<ProductVM>.CreateAsync(data, pageNumber ?? 1, pageSize));
        }

        [Authorize]
        public IActionResult AddToWishList(int DetailId)
        {
            int customerId = int.Parse(User.FindFirst("UserID").Value);

            var wishItem = DBContext.TblUserWishlists.SingleOrDefault(p => p.BookDetailId == DetailId);
            if (wishItem != null) {
                return Redirect(Request.Headers["Referer"].ToString());
            }

            wishItem = new TblUserWishlist
            {
                UserId = customerId,
                BookDetailId = DetailId
            };
            DBContext.Database.BeginTransaction();
            try
            {
                DBContext.Database.CommitTransaction();
                DBContext.Add(wishItem);
                DBContext.SaveChanges();

                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch
            {
                DBContext.Database.RollbackTransaction();
            }
            return Redirect(Request.Headers["Referer"].ToString());
        }

    }
}

Views/Products/BestSelling.cshtml
@{
    ViewData["Title"] = "Best Selling";
    Layout = "_ProductsList";
}

@model PaginatedList<BookStore2024.ViewModels.ProductVM>

@section BreadCrumb {
    <div class="tg-innerbanner tg-haslayout tg-parallax tg-bginnerbanner" data-z-index="-100" data-appear-top-offset="600" data-parallax="scroll" data-image-src="../images/parallax/bgparallax-07.jpg">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="tg-innerbannercontent">
                        <h1>Best Selling</h1>
                        <ol class="tg-breadcrumb">
                            <li><a href="javascript:void(0);">home</a></li>
                            <li class="tg-active">Best Selling</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="tg-productgrid">
    <div class="tg-refinesearch">
        <span>showing @(ViewBag.PageSize * (Model.PageIndex - 1) + 1) to @(ViewBag.PageSize * (Model.PageIndex - 1) + Model.Count()) of @ViewBag.totalProduct total</span>
        <form class="tg-formtheme tg-formsortshoitems">
            <fieldset>
                <div class="form-group">
                    <label>sort by:</label>
                    <span class="tg-select">
                        <select>
                            <option>name</option>
                            <option>name</option>
                            <option>name</option>
                        </select>
                    </span>
                </div>
                <div class="form-group">
                    <label>show:</label>
                    <span class="tg-select">
                        <select>
                            <option>8</option>
                            <option>16</option>
                            <option>20</option>
                        </select>
                    </span>
                </div>
            </fieldset>
        </form>
    </div>
    @foreach (var item in Model)
    {
        <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3">
            @await Html.PartialAsync("ProductItem", item)
        </div>
    }
    @if (Model.TotalPages >= 2)
    {
        <div class="Paging row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                @if (Model.HasPreviousPage)
                {
                    <a asp-action="BestSelling"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-category="@ViewBag.category"
                       asp-route-genre="@ViewBag.genre"
                       class="btn btn-default">
                        Previous
                    </a>
                }

                @for (var i = 1; i <= Model.TotalPages; i++)
                {
                    <a asp-action="BestSelling"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber=@i
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-category="@ViewBag.category"
                       asp-route-genre="@ViewBag.genre"
                       class="btn btn-default">
                        @i
                    </a>

                }

                @if (Model.HasNextPage)
                {
                    <a asp-action="BestSelling"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       asp-route-category="@ViewBag.category"
                       asp-route-genre="@ViewBag.genre"
                       class="btn btn-default">
                        Next
                    </a>
                }
            </div>
        </div>
    }
    
</div>

Views/Products/Detail.cshtml
@{
    ViewData["Title"] = "Search";
    Layout = "_ProductsList";
}
@model BookStore2024.ViewModels.ProductVM

@section BreadCrumb {
<div class="tg-innerbanner tg-haslayout tg-parallax tg-bginnerbanner" data-z-index="-100" data-appear-top-offset="600" data-parallax="scroll" data-image-src="../images/parallax/bgparallax-07.jpg">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="tg-innerbannercontent">
                    <h1>All Products</h1>
                    <ol class="tg-breadcrumb">
                        <li><a href="javascript:void(0);">home</a></li>
                        <li><a href="javascript:void(0);">Products</a></li>
                        <li class="tg-active">@Model.ProductName</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
}
<div class="tg-productdetail">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="tg-postbook">
                <figure class="tg-featureimg">
                    <img src="@Model.ProductImg" alt="ProductImg">
                </figure>
                <div class="tg-postbookcontent">
                    <span class="tg-bookprice">
                        @if (Model.Discount != 0)
                        {
                            <ins>$@(Model.Price - Model.Discount)</ins>
                            <del>$@Model.Price</del>
                        }
                        @if (Model.Discount == 0)
                        {
                            <ins>$@Model.Price</ins>
                        }
                    </span>
                    @if (Model.Discount != 0)
                    {
                        <span class="tg-bookwriter">You save: $@Model.Discount</span>
                    }
                    <ul class="tg-delevrystock">
                        <li><i class="icon-rocket"></i><span>Free delivery worldwide</span></li>
                        <li><i class="icon-checkmark-circle"></i><span>Dispatch from the USA in 2 working days </span></li>
                        @if(Model.StockQuantity > 0)
                        {
                            <li><i class="icon-store"></i><span>Status: <em>In Stock</em></span></li>
                        }else{
                            <li><i class="icon-store"></i><span>Status: <em>Out Stock</em></span></li>
                        }
                        
                    </ul>
                    <form asp-action="AddtoCart" asp-controller="Cart" asp-route-productDetailId="@Model.BookDetailId">
                        <div class="tg-quantityholder">
                            <button type="button" style="background-color: transparent"><em class="minus">-</em></button>
                                <input type="text" class="result" value="1" id="quantity1" name="quantity"/>
                            <button type="button" style="background-color: transparent"><em class="plus">+</em></button>
                        </div>
                        <button class="tg-btn tg-active tg-btn-lg btn-add-tocart">Add To Cart</button>
                    </form>
                    <a class="tg-btnaddtowishlist" href="javascript:void(0);">
                        <span>add to wishlist</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <div class="tg-productcontent">
                <ul class="tg-bookscategories">
                    <li><a href="javascript:void(0);">@Model.CategoryName - @Model.GenreName</a></li>
                </ul>
                @if (Model.Discount != 0)
                {
                    <div class="tg-themetagbox">
                        <span class="tg-themetag">sale</span>
                    </div>
                }
                <div class="tg-booktitle">
                    <h3>@Model.ProductName</h3>
                </div>
                <span class="tg-bookwriter">By: <a asp-action="Detail" asp-controller="Author" asp-route-DetailId="@Model.AuthorId">@Model.AuthorName</a></span>
                <span class="tg-stars"><span></span></span>
                <span class="tg-addreviews"><a href="javascript:void(0);">Add Your Review</a></span>
                <div class="tg-share">
                    <span>Share:</span>
                    <ul class="tg-socialicons">
                        <li class="tg-facebook"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
                        <li class="tg-twitter"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
                        <li class="tg-linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
                        <li class="tg-googleplus"><a href="javascript:void(0);"><i class="fa fa-google-plus"></i></a></li>
                        <li class="tg-rss"><a href="javascript:void(0);"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
                <div class="tg-description">
                    <p>@Model.ProductDescription</p>
                </div>
                <div class="tg-sectionhead">
                    <h2>Product Details</h2>
                </div>
                <ul class="tg-productinfo">
                    <li><span>Format:</span><span>@Model.FormatName</span></li>
                    <li><span>Pages:</span><span>@Model.Pages pages</span></li>
                    <li><span>Dimensions:</span><span>153 x 234 x 43mm | 758g</span></li>
                    <li><span>Publisher:</span><span>@Model.Publisher</span></li>
                    <li><span>Language:</span><span>@Model.Language</span></li>
                    <li><span>Illustrations note:</span><span>@Model.IllustrationsNote</span></li>
                    <li><span>ISBN10:</span><span>@Model.Isbn10</span></li>
                    <li><span>ISBN13:</span><span>@Model.Isbn13</span></li>
                    <li><span>Other Fomate:</span><span>CD-Audio, Paperback, E-Book</span></li>
                </ul>
                <div class="tg-alsoavailable">
                    <figure>
                        <img src="../images/img-02.jpg" alt="image description">
                        <figcaption>
                            <h3>Also Available in:</h3>
                            <ul>
                                <li><span>CD-Audio $18.30</span></li>
                                <li><span>Paperback $20.10</span></li>
                                <li><span>E-Book $11.30</span></li>
                            </ul>
                        </figcaption>
                    </figure>
                </div>
            </div>
        </div>
        
        <div class="tg-aboutauthor">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="tg-sectionhead">
                    <h2>About Author</h2>
                </div>
                <div class="tg-authorbox">
                    <figure class="tg-authorimg">
                        <img src="@Model.ProfileImageUrl" alt="Author img">
                    </figure>
                    <div class="tg-authorinfo">
                        <div class="tg-authorhead">
                            <div class="tg-leftarea">
                                <div class="tg-authorname">
                                    <h2>@Model.AuthorName</h2>
                                    <span>Author Since: June 27, 2017</span>
                                </div>
                            </div>
                            <div class="tg-rightarea">
                                <ul class="tg-socialicons">
                                    <li class="tg-facebook"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
                                    <li class="tg-twitter"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
                                    <li class="tg-linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
                                    <li class="tg-googleplus"><a href="javascript:void(0);"><i class="fa fa-google-plus"></i></a></li>
                                    <li class="tg-rss"><a href="javascript:void(0);"><i class="fa fa-rss"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="tg-description">
                            <p>Laborum sed ut perspiciatis unde omnis iste natus sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis etation.</p>
                        </div>
                        <a class="tg-btn tg-active" asp-action="Detail" asp-controller="Author" asp-route-DetailId="@Model.AuthorId">View All Books</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Products/ProductItem.cshtml
@* View định nghĩa 1 sản phẩm được hiển thị trong list dùng để sử dụng lại thuận tiện hơn *@
@model BookStore2024.ViewModels.ProductVM

<div class="tg-postbook">
    <figure class="tg-featureimg">
        <a asp-action="Detail" asp-controller="Products" asp-route-DetailId="@Model.BookDetailId">
            <div class="tg-bookimg">
                <div class="tg-frontcover"><img src="@Model.ProductImg" alt="ProductImg"></div>
                <div class="tg-backcover"><img src="@Model.ProductImg" alt="ProductImg"></div>
            </div>
        </a>
        <a class="tg-btnaddtowishlist" asp-action="AddToWishList" asp-controller="Products" asp-route-DetailId="@Model.BookDetailId" onclick="alert('added to wish list!')">
            <i class="icon-heart"></i>
            <span>add to wishlist</span>
        </a>

    </figure>
    <div class="tg-postbookcontent">
        <ul class="tg-bookscategories">
            <li><a href="javascript:void(0);">@Model.CategoryName</a></li>
        </ul>
        @if (Model.Discount != 0)
        {
            <div class="tg-themetagbox">
                <span class="tg-themetag">sale</span>
            </div>
        }
        <div class="tg-booktitle">
            <h3>
                <a asp-action="Detail" asp-controller="Products" asp-route-DetailId="@Model.BookDetailId">
                    @Model.ProductName |[@Model.FormatName]
                </a>
            </h3>
        </div>
        <span class="tg-bookwriter">By: <a href="javascript:void(0);">@Model.AuthorName</a></span>
        <span class="tg-stars"><span></span></span>
        <span class="tg-bookprice">
            @if (Model.Discount != 0)
            {
                <ins>$@(Model.Price - Model.Discount)</ins>
                <del>$@Model.Price</del>
            }
            @if (Model.Discount == 0)
            {
                <ins>$@Model.Price</ins>
            }
        </span>
        <a class="tg-btn tg-btnstyletwo btn-add-tocart" asp-action="AddtoCart" asp-controller="Cart" asp-route-productDetailId="@Model.BookDetailId">
            <i class="fa fa-shopping-basket"></i>
            <em>Add To Cart</em>
        </a>
    </div>
</div>